[package]
name = "acerbus-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", default-features = false }
bevy_renet = "0.0.4"
serde = { version = "1.0.140", features = ["derive"] }
